version: "3.8"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    volumes:
      - .:/usr/app
    network_mode: "host"
    depends_on:
      - database_rentx

volumes:
  pgdata: